
- platform: modbus
  registers:
    - { name: Temperatura wiatrolap,                   unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1000 }
    - { name: Temperatura wiatrolap podloga,           unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1002 }
    - { name: Temperatura wiatrolap zadana,            unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1006 }
    - { name: Temperatura techniczne,                  unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1020 }
    - { name: Temperatura techniczne podloga,          unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1022 }
    - { name: Temperatura techniczne zadana,           unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1026 }
    - { name: Temperatura lazienka dol,                unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1040 }
    - { name: Temperatura lazienka dol podloga,        unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1042 }
    - { name: Temperatura lazienka dol zadana,         unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1046 }
    - { name: Temperatura salon schody,                unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1060 }
    - { name: Temperatura salon schody podloga,        unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1062 }
    - { name: Temperatura salon schody zadana,         unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1066 }
    - { name: Temperatura salon przejscie,             unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1080 }
    - { name: Temperatura salon przejscie podloga,     unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1082 }
    - { name: Temperatura salon przejscie zadana,      unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1086 }
    - { name: Temperatura kuchnia,                     unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1100 }
    - { name: Temperatura kuchnia podloga,             unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1102 }
    - { name: Temperatura kuchnia zadana,              unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1106 }
    - { name: Temperatura garderoba,                   unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1120 }
    - { name: Temperatura garderoba podloga,           unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1122 }
    - { name: Temperatura garderoba zadana,            unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1126 }
    - { name: Temperatura pralnia,                     unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1140 }
    - { name: Temperatura pralnia podloga,             unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1142 }
    - { name: Temperatura pralnia zadana,              unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1146 }
    - { name: Temperatura lazienka gora,               unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1160 }
    - { name: Temperatura lazienka gora podloga,       unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1162 }
    - { name: Temperatura lazienka gora zadana,        unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1166 }
    - { name: Temperatura korytarz gora,               unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1180 }
    - { name: Temperatura korytarz gora podloga,       unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1182 }
    - { name: Temperatura korytarz gora zadana,        unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1186 }
    - { name: Temperatura sypialnia Ewy,               unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1200 }
    - { name: Temperatura sypialnia Ewy podloga,       unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1202 }
    - { name: Temperatura sypialnia Ewy zadana,        unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1206 }
    - { name: Temperatura sypialnia Ady,               unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1220 }
    - { name: Temperatura sypialnia Ady podloga,       unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1222 }
    - { name: Temperatura sypialnia Ady zadana,        unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1226 }
    - { name: Temperatura sypialnia rodzicow,          unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1240 }
    - { name: Temperatura sypialnia rodzicow podloga,  unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1242 }
    - { name: Temperatura sypialnia rodzicow zadana,   unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1246 }
    - { name: Temperatura zewnetrzna polnoc,           unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1400 }
    - { name: Temperatura zewnetrzna poludnie,         unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1401 }
    - { name: Wilgotnosc salon schody,                 unit_of_measurement: '%', scale: 0.01, precision: 2, slave: 1,  register: 1404 }
    - { name: Wilgotnosc zewnetrzna,                   unit_of_measurement: '%', scale: 0.01, precision: 2, slave: 1,  register: 1406 }

- platform: template
  sensors:
    temperatura_zewnetrzna_polnoc_przeliczona:
      unit_of_measurement: °C
      entity_id: sensor.temperatura_zewnetrzna_polnoc
      value_template: >
        {% if states('sensor.temperatura_zewnetrzna_polnoc') | float > 100 %}
          {{ "%.2f" | format ( ( states('sensor.temperatura_zewnetrzna_polnoc') | float ) - 655.36 )  }}
        {% elif states('sensor.temperatura_zewnetrzna_polnoc') | float > 0 %}
          {{ states('sensor.temperatura_zewnetrzna_polnoc') }}
        {% else %}
          -
        {% endif %}
    temperatura_zewnetrzna_poludnie_przeliczona:
      unit_of_measurement: °C
      entity_id: sensor.temperatura_zewnetrzna_poludnie
      value_template: >
        {% if states('sensor.temperatura_zewnetrzna_poludnie') | float > 100 %}
          {{ "%.2f" | format ( ( states('sensor.temperatura_zewnetrzna_poludnie') | float ) - 655.36 )  }}
        {% elif states('sensor.temperatura_zewnetrzna_poludnie') | float > 0 %}
          {{ states('sensor.temperatura_zewnetrzna_poludnie') }}
        {% else %}
          -
        {% endif %}
    temperatura_dol:
      unit_of_measurement: °C
      entity_id: sensor.temperatura_salon_schody, sensor.temperatura_salon_przejscie
      value_template: >
        {{ "%.2f" | format (( states('sensor.temperatura_salon_schody') | float +  states('sensor.temperatura_salon_przejscie') | float ) / 2 ) }}
    temperatura_sypialnie:
      unit_of_measurement: °C
      entity_id: sensor.temperatura_sypialnia_ady, sensor.temperatura_sypialnia_ewy, sensor.temperatura_sypialnia_rodzicow
      value_template: >
        {{ "%.2f" | format ( (  states('sensor.temperatura_sypialnia_ady') | float +  states('sensor.temperatura_sypialnia_rodzicow') | float +  states('sensor.temperatura_sypialnia_ewy') | float ) / 3 )  }}

- platform: command_line
  name: Moc wentylatora
  command: "cat /home/homeassistant/.homeassistant/scripts/fan_speed"
  scan_interval: 5

- platform: time_date
  display_options: 'date_time'

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /home
    - type: memory_free
    - type: memory_use
    - type: processor_use
#    - type: swap_free
#    - type: swap_use
    - type: since_last_boot

- platform: cpuspeed
  name: CPU

- platform: moon

- platform: darksky
  api_key: !secret darksky_api_key
  update_interval: '00:10'
  monitored_conditions:
#      - summary
#      - icon
#      - nearest_storm_distance
#      - nearest_storm_bearing
#      - precip_type
#      - precip_intensity
    - precip_probability
    - temperature
    - apparent_temperature
#     - dew_point
    - wind_speed
    - wind_bearing
    - cloud_cover
#      - humidity
    - pressure
#      - visibility
#      - ozone
#      - minutely_summary
#      - hourly_summary
#      - daily_summary
#      - temperature_max
#      - temperature_min
#      - apparent_temperature_max
#      - apparent_temperature_min
#      - precip_intensity_max

# Weather Prediction
#sensor weather:
#  - platform: yr
#    monitored_conditions:
#      - temperature
#      - symbol
#      - precipitation
#      - windSpeed
#      - pressure
#      - windDirection
#      - humidity
#      - fog
#      - cloudiness
#      - lowClouds
#      - mediumClouds
#      - highClouds
#      - dewpointTemperature


