homeassistant:
  # Name of the location where Home Assistant is running
  name: Złoty Potok
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Warsaw
  customize: !include customize.yaml

config:

#
# Show links to resources in log and frontend
# introduction:

zone: !include zones.yaml

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123
  trusted_networks:
    - 127.0.0.1
    - 192.168.88.0/24
  ip_ban_enabled: True
  login_attempts_threshold: 5


media_player:
  - platform: yamaha
    name: Yamaha Potok
    host: 192.168.88.37
#  - platform: yamaha_musiccast
#    name: Yamaha Potok
#    host: 192.168.88.37
  - platform: yamaha
    name: Yamaha Bedzin
    host: 192.168.10.245
  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret
#  - platform: samsungtv
#    name: Samsung TV Potok
#    host: 192.168.88.21
#    mac: 84:A4:66:60:7F:9D
#  - platform: samsungtv
#    name: Samsung TV Bedzin
#    host: 192.168.88.251
#    host: 192.168.0.20
#    mac: 84:A4:66:60:7F:9D

# Checks for available updates
updater:

# Discover some devices automatically
# discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
# conversation:

panel_iframe:
  netatmo_potok:
    title: 'Netatmo ZP'
    url: 'https://my.netatmo.com/app/weather'
    icon: 'mdi:weather-windy'
  forecast_potok:
    title: 'Złoty Potok'
#    url: 'http://forecast.io/embed/#lat=50.7180&lon=19.4290&units=ca&name=Złoty Potok'
    url: 'http://www.meteo.pl/php/meteorogram_id_coamps.php?ntype=2n&id=751'
    icon: 'mdi:weather-partlycloudy'
  forecast_bedzin:
    title: 'Będzin'
    url: 'http://www.meteo.pl/php/meteorogram_id_coamps.php?ntype=2n&id=705'
    icon: 'mdi:weather-partlycloudy'
  forecast_bedzin2:
    title: 'Będzin2'
    url: 'https://nowe.meteo.pl/mgram.php?model=2&mgram_url=%2Fcoamps%2Fmgram%2Fmgram_pict.php%3Fntype%3D2n%26row%3D149%26col%3D86%26lang%3Dpl'
    icon: 'mdi:weather-partlycloudy'


# Enables support for tracking state changes over time.
history:
#  include:
#    domains:
#      - binary_sensor
#      - sensor
#  exclude:
#    entities:
#      - sensor.cpu
#      - sensor.cpu_used
#      - sensor.date__time
#      - sensor.disk_use_percent_home
#      - sensor.moc_wentylatora
#      - sensor.moon
#      - sensor.memory_free
#      - sensor.memory_use
#      - sensor.last_boot

recorder:
  purge_interval: 1
  purge_keep_days: 14
# Use the include list to define the domains/entities to record, and exclude some of them with in the exclude list. 
# This makes sense if you for instance include the sensor domain, but want to exclude some specific sensors.
#  include:
#    domains:
#      - binary_sensor
#      - sensor
#  exclude:
#    entities:
#      - sensor.cpu
#      - sensor.cpu_used
#      - sensor.date__time
#      - sensor.disk_use_percent_home
#      - sensor.moc_wentylatora
#      - sensor.moon
#      - sensor.memory_free
#      - sensor.memory_use
#      - sensor.last_boot
  include:
    entities:
      - binary_sensor.camera_door_motion
      - binary_sensor.camera_door_pir_alarm
      - binary_sensor.camera_fence_1_disk_error
      - binary_sensor.camera_fence_1_motion
      - binary_sensor.camera_fence_2_disk_error
      - binary_sensor.camera_fence_2_motion
      - binary_sensor.camera_gate_disk_error_2
      - binary_sensor.camera_gate_motion_2
      - binary_sensor.camera_gate_pir_alarm_2
      - binary_sensor.camera_gate_tamper_detection_2
      - binary_sensor.grzanie_garderoba
      - binary_sensor.grzanie_korytarz_gora
      - binary_sensor.grzanie_kuchnia
      - binary_sensor.grzanie_lazienka_dol
      - binary_sensor.grzanie_lazienka_gora
      - binary_sensor.grzanie_pralnia
      - binary_sensor.grzanie_salon
      - binary_sensor.grzanie_salon_przejscie
      - binary_sensor.grzanie_sypialnia_ady
      - binary_sensor.grzanie_sypialnia_ewy
      - binary_sensor.grzanie_sypialnia_rodzicow
      - binary_sensor.grzanie_techniczne
      - binary_sensor.grzanie_wiatrolap
      - binary_sensor.living_room_pir_alarm
      - binary_sensor.tool_house_disk_error
      - binary_sensor.tool_house_motion
      - binary_sensor.tool_house_tamper_detection
      - sensor.netatmo_indoor_co2_2
      - sensor.netatmo_indoor_humidity_2
      - sensor.netatmo_indoor_noise_2
      - sensor.netatmo_indoor_pressure_2
      - sensor.netatmo_indoor_temperature_2
      - sensor.temperatura_dol
      - sensor.temperatura_garderoba
      - sensor.temperatura_garderoba_podloga
      - sensor.temperatura_korytarz_gora
      - sensor.temperatura_korytarz_gora_podloga
      - sensor.temperatura_kuchnia
      - sensor.temperatura_kuchnia_podloga
      - sensor.temperatura_lazienka_dol
      - sensor.temperatura_lazienka_dol_podloga
      - sensor.temperatura_lazienka_gora
      - sensor.temperatura_lazienka_gora_podloga
      - sensor.temperatura_pralnia
      - sensor.temperatura_pralnia_podloga
      - sensor.temperatura_salon_przejscie
      - sensor.temperatura_salon_przejscie_podloga
      - sensor.temperatura_salon_schody
      - sensor.temperatura_salon_schody_podloga
      - sensor.temperatura_sypialnia_ady
      - sensor.temperatura_sypialnia_ady_podloga
      - sensor.temperatura_sypialnia_ewy
      - sensor.temperatura_sypialnia_ewy_podloga
      - sensor.temperatura_sypialnia_rodzicow
      - sensor.temperatura_sypialnia_rodzicow_podloga
      - sensor.temperatura_sypialnie
      - sensor.temperatura_techniczne
      - sensor.temperatura_techniczne_podloga
      - sensor.temperatura_wiatrolap
      - sensor.temperatura_wiatrolap_podloga
      - sensor.temperatura_zewnetrzna_polnoc_przeliczona
      - sensor.temperatura_zewnetrzna_poludnie_przeliczona
      - sensor.wilgotnosc_salon_schody
      - sensor.wilgotnosc_zewnetrzna


# View all events in a logbook
logbook:

logger: 
  default: warn
#  default: debug
  logs: 
#    homeassistant.components.switch: debug
    homeassistant.components.media_player: critical
    homeassistant.components.camera: critical

# Track the sun
sun:

weblink:
  entities:
    - name: Router
      url: http://192.168.88.1
    - name: Drukarka
      url: http://192.168.88.15

notify:
  - name: Gmail
    platform: smtp
    server: smtp.gmail.com
    port: 587
    sender: !secret gmail_sender
    starttls: true
    username: !secret gmail_username
    password: !secret gmail_password
    recipient: !secret gmail_recipient

# Text to speech
# tts:
#   platform: google

map:

mqtt:
  broker: !secret mqtt_broker 
  port: !secret mqtt_port
  certificate: auto
  username: !secret mqtt_username
  password: !secret mqtt_password
#  embedded:
#    listeners:
#      default:
#        max-connections: 50000
#        type: tcp
#      my-tcp-1:
#        bind: 127.0.0.1:1883
#      my-tcp-2:
#        bind: 1.2.3.4:1884
#        max-connections: 1000
#      my-tcp-ssl-1:
#        bind: 127.0.0.1:8885
#        ssl: on
#        cafile: /some/cafile
#        capath: /some/folder
#        capath: certificate data
#        certfile: /some/certfile
#        keyfile: /some/key
#    my-ws-1:
#        bind: 0.0.0.0:8080
#        type: ws
#    timeout-disconnect-delay: 2
#  auth:
#    plugins: ['auth.anonymous'] #List of plugins to activate for authentication among all registered plugins
#    allow-anonymous: true / false
#    password-file: /some/passwd_file

owntracks:

modbus: { type: serial, method: rtu, port: /dev/serial0, baudrate: 115200, stopbits: 1, bytesize: 8, parity: N }
#modbus: { type: tcp, host: 192.168.88.10, port: 502 }

switch Lampy:
  platform: modbus
  slave: 1
  coils: 
    - { name: Lampa Salon sufit,          slave: 1, coil: 32 }
    - { name: Lampa Salon kinkiety,       slave: 1, coil: 33 }
    - { name: Lampa Jadalnia sufit,       slave: 1, coil: 34 }
    - { name: Lampa Salon kanapa,         slave: 1, coil: 35 }
    - { name: Lampa Taras,                slave: 1, coil: 36 }
    - { name: Lampa Kuchnia sufit,        slave: 1, coil: 37 }
    - { name: Lampa Lazienka dol,         slave: 1, coil: 38 }
    - { name: Lampa Lazienka dol lustro,  slave: 1, coil: 39 }
    - { name: Lampa Korytarz dol,         slave: 1, coil: 40 }
    - { name: Lampa Techniczne,           slave: 1, coil: 41 }
    - { name: Lampa Wiatrolap,            slave: 1, coil: 42 }
    - { name: Lampa Osw2,                 slave: 1, coil: 43 }
    - { name: Lampa Schody,               slave: 1, coil: 44 }
    - { name: Lampa Drzwi,                slave: 1, coil: 45 }
    - { name: Lampa Pralnia 1,            slave: 1, coil: 46 }
    - { name: Lampa Pralnia 1A,           slave: 1, coil: 47 }
    - { name: Lampa Lazienka gora,        slave: 1, coil: 48 }
    - { name: Lampa Lazienka gora lustro, slave: 1, coil: 49 }
    - { name: Lampa Garderoba,            slave: 1, coil: 50 }
    - { name: Lampa Sypialnia rodzicow,   slave: 1, coil: 51 }
    - { name: Lampa Sypialnia Ady,        slave: 1, coil: 52 }
    - { name: Lampa Sypialnia Ewy,        slave: 1, coil: 53 }
    - { name: Lampa Korytarz pralnia,     slave: 1, coil: 54 }
    - { name: Lampa Schody gora,          slave: 1, coil: 55 }
    - { name: Lampa Kuchnia zlew,         slave: 1, coil: 24 }
    - { name: Lampa Kuchnia okap,         slave: 1, coil: 25 }
    - { name: Stycznik strych,            slave: 1, coil: 26 }
    - { name: Stycznik gniazda parter,    slave: 1, coil: 0  }
    - { name: Stycznik gniazda gora,      slave: 1, coil: 1  }
    - { name: Stycznik podgrzewacze lazienki,  slave: 1, coil: 2 }
    - { name: Stycznik kuchnia,           slave: 1, coil: 3  }
  registers:
    - { name: L1_state,     slave: 1, register: 100, command_on: 1, command_off: 0 }
    - { name: L1_updatereq, slave: 1, register: 101, command_on: 1, command_off: 0  }
    - { name: L2_state,     slave: 1, register: 102, command_on: 1, command_off: 0  }
    - { name: L2_updatereq, slave: 1, register: 103, command_on: 1, command_off: 0  }
    - { name: L3_state,     slave: 1, register: 104, command_on: 1, command_off: 0  }
    - { name: L3_updatereq, slave: 1, register: 105, command_on: 1, command_off: 0  }
    - { name: L4_state,     slave: 1, register: 106, command_on: 1, command_off: 0  }
    - { name: L4_updatereq, slave: 1, register: 107, command_on: 1, command_off: 0  }
    - { name: L5_state,     slave: 1, register: 108, command_on: 1, command_off: 0  }
    - { name: L5_updatereq, slave: 1, register: 109, command_on: 1, command_off: 0  }


switch update_pics:
  platform: command_line
  switches:
    update_pics:
      command_on: "/home/homeassistant/.homeassistant/scripts/get_pics.sh"
      command_off: "echo"

#input_slider: 
#  ventilation:
#    name: Ventilation
#    initial: 3
#    min: 0
#    max: 5
#    step: 1
#    icon: mdi:fan

input_number: 
  ventilation:
    name: Ventilation
    initial: 3
    min: 0
    max: 5
    step: 1
    icon: mdi:fan
  random_hour:
    min: 0
    max: 23
  random_minute:
    min: 0
    max: 59

input_select:
  log_level:
    name: Log Level
    options:
      - critical
      - fatal
      - error
      - warning
      - warn
      - info
      - debug
      - notset
    initial: warn

tradfri:
  host: 192.168.88.36
#  api_key: !secret ikea_tradfri_security_code
  allow_tradfri_groups: false

sensor: !include sensors.yaml

switch grzanie:
    platform: modbus
    slave: 1
    coils:
#      - { name: Grzanie salon przejscie, slave: 1, coil: 8, control: hidden } # syntax change 0.58
      - { name: Grzanie salon przejscie, slave: 1, coil: 8 }

      - { name: Grzanie techniczne, slave: 1, coil: 9  }
      - { name: Grzanie wiatrolap, slave: 1, coil: 10 }
      - { name: Grzanie kuchnia, slave: 1, coil: 11 }
      - { name: Grzanie salon, slave: 1, coil: 10 }
      - { name: Grzanie lazienka dol, slave: 1, coil: 12 }
      - { name: Grzanie pralnia, slave: 1, coil: 13 }
      - { name: Grzanie korytarz gora, slave: 1, coil: 14 }
      - { name: Grzanie garderoba, slave: 1, coil: 15 }
      - { name: Grzanie sypialnia rodzicow, slave: 1, coil: 16 }
      - { name: Grzanie sypialnia Ady, slave: 1, coil: 17 }
      - { name: Grzanie sypialnia Ewy, slave: 1, coil: 18 }
      - { name: Grzanie lazienka gora, slave: 1, coil: 19 }

binary_sensor Grzanie:
  - platform: template
    sensors:
      grzanie_salon_przejscie:
        value_template: "{{ states.switch.grzanie_salon_przejscie.state == 'on' }}"
#        entity_id: switch.grzanie_salon_przejscie
      grzanie_techniczne:
        value_template: "{{ states.switch.grzanie_techniczne.state == 'on' }}"
#        entity_id: switch.grzanie_techniczne
      grzanie_wiatrolap:
        value_template: "{{ states.switch.grzanie_wiatrolap.state == 'on' }}"
#        entity_id: switch.grzanie_wiatrolap
      grzanie_kuchnia:
        value_template: "{{ states.switch.grzanie_kuchnia.state == 'on' }}"
#        entity_id: switch.grzanie_kuchnia
      grzanie_salon:
        value_template: "{{ states.switch.grzanie_salon.state == 'on' }}"
#        entity_id: switch.grzanie_salon
      grzanie_lazienka_dol:
        value_template: "{{ states.switch.grzanie_lazienka_dol.state == 'on' }}"
#        entity_id: switch.grzanie_lazienka_dol
      grzanie_pralnia:
        value_template: "{{ states.switch.grzanie_pralnia.state == 'on' }}"
#        entity_id: switch.grzanie_pralnia
      grzanie_korytarz_gora:
        value_template: "{{ states.switch.grzanie_korytarz_gora.state == 'on' }}"
#        entity_id: switch.grzanie_korytarz_gora
      grzanie_garderoba:
        value_template: "{{ states.switch.grzanie_garderoba.state == 'on' }}"
#        entity_id: switch.grzanie_garderoba
      grzanie_sypialnia_rodzicow:
        value_template: "{{ states.switch.grzanie_sypialnia_rodzicow.state == 'on' }}"
#        entity_id: switch.grzanie_sypialnia_rodzicow
      grzanie_sypialnia_ady:
        value_template: "{{ states.switch.grzanie_sypialnia_ady.state == 'on' }}"
#        entity_id: switch.grzanie_sypialnia_ady
      grzanie_sypialnia_ewy:
        value_template: "{{ states.switch.grzanie_sypialnia_ewy.state == 'on' }}"
#        entity_id: switch.grzanie_sypialnia_ewy
      grzanie_lazienka_gora:
        value_template: "{{ states.switch.grzanie_lazienka_gora.state == 'on' }}"
#        entity_id: switch.grzanie_lazienka_gora

ffmpeg: 
  ffmpeg_bin: /usr/bin/avconv

camera: 
  - platform: local_file
    file_path: /home/homeassistant/.homeassistant/www/local/drzwi.jpg
    name: Kamera drzwi
  - platform: local_file
    file_path: /home/homeassistant/.homeassistant/www/local/salon.jpg
    name: Kamera salon
  - platform: local_file
    file_path: /home/homeassistant/.homeassistant/www/local/brama.jpg
    name: Kamera brama
  - platform: local_file
    file_path: /home/homeassistant/.homeassistant/www/local/narzedziowy.jpg
    name: Kamera narzedziowy
  - platform: local_file
    file_path: /home/homeassistant/.homeassistant/www/local/furtka.jpg
    name: Kamera furtka
  - platform: local_file
    file_path: /home/homeassistant/.homeassistant/www/local/podjazd.jpg
    name: Kamera podjazd

#  - platform: local_file
#    file_path: /home/homeassistant/.homeassistant/www/local/ptaki.jpg
#    name: Kamera ptaki

#  - platform: ffmpeg
#    name: Kamera drzwi ffmpeg
#    input: rtsp://user:pass@192.168.88.101:554/Streaming/Channels/2
#    extra_arguments: '--q:v 2'
#  - platform: ffmpeg
#    input: rtsp://user:pass@192.168.88.101:554/Streaming/Channels/1
#    name: Kamera drzwi hi-res
#  - platform: generic
#    name: Kamera drzwi
#    still_image_url: http://192.168.88.101/Streaming/channels/1/picture
#    username: !secret kamera_drzwi_username
#    password: !secret kamera_drzwi_password
#  - platform: generic
#    name: Kamera TPLink
#    still_image_url: http://192.168.88.102:8080/stream/snapshot.jpg
#    username: !secret kamera_tplink_username
#    password: !secret kamera_tplink_password
#    scan_interval: 20

device_tracker: !include device_tracker.yaml

shell_command:
  post_fan_speed: /home/homeassistant/.homeassistant/scripts/post_fan_speed
  get_pics: /home/homeassistant/.homeassistant/scripts/get_pics.sh

switch:
  platform: command_line
  switches:
    lampa_ogrod_wjazd:
      command_on: "/home/homeassistant/.homeassistant/scripts/lampa_ogrod_wjazd_on.sh"
      command_off: "/home/homeassistant/.homeassistant/scripts/lampa_ogrod_wjazd_off.sh"
      command_state: "/home/homeassistant/.homeassistant/scripts/lampa_ogrod_wjazd_state.sh"
    lampa_ogrod_wiata:
      command_on: "/home/homeassistant/.homeassistant/scripts/lampa_ogrod_wiata_on.sh"
      command_off: "/home/homeassistant/.homeassistant/scripts/lampa_ogrod_wiata_off.sh"
      command_state: "/home/homeassistant/.homeassistant/scripts/lampa_ogrod_wiata_state.sh"

binary_sensor kamera_salon:
  platform: hikvision
  host: 192.168.88.100
  port: 80
  ssl: False
  username: !secret kamera_salon_pir_username
  password: !secret kamera_salon_pir_password
#  customize:
#    sensor_name_1:
#      delay: 30
#    sensor_name_2:
#      ignored: True

binary_sensor kamera_drzwi:
  platform: hikvision
  host: 192.168.88.101
  port: 80
  ssl: False
  username: !secret kamera_drzwi_pir_username
  password: !secret kamera_drzwi_pir_password

binary_sensor kamera_brama:
  platform: hikvision
  host: 192.168.88.103
  port: 80
  ssl: False
  username: !secret kamera_brama_pir_username
  password: !secret kamera_brama_pir_password

binary_sensor kamera_narzedziowy:
  platform: hikvision
  host: 192.168.88.104
  port: 80
  ssl: False
  username: !secret kamera_narzedziowy_pir_username
  password: !secret kamera_narzedziowy_pir_password

binary_sensor kamera_furtka:
  platform: hikvision
  host: 192.168.88.108
  port: 80
  ssl: False
  username: !secret kamera_furtka_pir_username
  password: !secret kamera_furtka_pir_password

binary_sensor kamera_podjazd:
  platform: hikvision
  host: 192.168.88.107
  port: 80
  ssl: False
  username: !secret kamera_podjazd_pir_username
  password: !secret kamera_podjazd_pir_password

netatmo: 
  api_key: !secret netatmo_client_id
  secret_key: !secret netatmo_client_secret
  username: !secret netatmo_username
  password: !secret netatmo_password

light: !include light.yaml

automation: !include automations.yaml

group: !include groups.yaml

scene: !include scenes.yaml

script: !include scripts.yaml
