
- platform: modbus
  registers:
    - { name: Temperatura wiatrolap,                   unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1000 }
    - { name: Temperatura wiatrolap podloga,           unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1002 }
    - { name: Temperatura wiatrolap zadana,            unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1006 }
    - { name: Temperatura techniczne,                  unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1020 }
    - { name: Temperatura techniczne podloga,          unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1022 }
    - { name: Temperatura techniczne zadana,           unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1026 }
    - { name: Temperatura lazienka dol,                unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1040 }
    - { name: Temperatura lazienka dol podloga,        unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1042 }
    - { name: Temperatura lazienka dol zadana,         unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1046 }
    - { name: Temperatura salon schody,                unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1060 }
    - { name: Temperatura salon schody podloga,        unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1062 }
    - { name: Temperatura salon schody zadana,         unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1066 }
    - { name: Temperatura salon przejscie,             unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1080 }
    - { name: Temperatura salon przejscie podloga,     unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1082 }
    - { name: Temperatura salon przejscie zadana,      unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1086 }
    - { name: Temperatura kuchnia,                     unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1100 }
    - { name: Temperatura kuchnia podloga,             unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1102 }
    - { name: Temperatura kuchnia zadana,              unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1106 }
    - { name: Temperatura garderoba,                   unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1120 }
    - { name: Temperatura garderoba podloga,           unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1122 }
    - { name: Temperatura garderoba zadana,            unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1126 }
    - { name: Temperatura pralnia,                     unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1140 }
    - { name: Temperatura pralnia podloga,             unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1142 }
    - { name: Temperatura pralnia zadana,              unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1146 }
    - { name: Temperatura lazienka gora,               unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1160 }
    - { name: Temperatura lazienka gora podloga,       unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1162 }
    - { name: Temperatura lazienka gora zadana,        unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1166 }
    - { name: Temperatura korytarz gora,               unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1180 }
    - { name: Temperatura korytarz gora podloga,       unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1182 }
    - { name: Temperatura korytarz gora zadana,        unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1186 }
    - { name: Temperatura sypialnia Ewy,               unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1200 }
    - { name: Temperatura sypialnia Ewy podloga,       unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1202 }
    - { name: Temperatura sypialnia Ewy zadana,        unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1206 }
    - { name: Temperatura sypialnia Ady,               unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1220 }
    - { name: Temperatura sypialnia Ady podloga,       unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1222 }
    - { name: Temperatura sypialnia Ady zadana,        unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1226 }
    - { name: Temperatura sypialnia rodzicow,          unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1240 }
    - { name: Temperatura sypialnia rodzicow podloga,  unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1242 }
    - { name: Temperatura sypialnia rodzicow zadana,   unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1246 }
    - { name: Temperatura zewnetrzna polnoc,           unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1400 }
    - { name: Temperatura zewnetrzna poludnie,         unit_of_measurement: °C, scale: 0.01, precision: 2, slave: 1,  register: 1401 }
    - { name: Wilgotnosc salon schody,                 unit_of_measurement: '%', scale: 0.01, precision: 2, slave: 1,  register: 1404 }
    - { name: Wilgotnosc zewnetrzna,                   unit_of_measurement: '%', scale: 0.01, precision: 2, slave: 1,  register: 1406 }

- platform: template
  sensors:
    temperatura_zewnetrzna_polnoc_przeliczona:
      unit_of_measurement: °C
#      entity_id: sensor.temperatura_zewnetrzna_polnoc
      value_template: >
        {{ states('sensor.temperatura_zewnetrzna_polnoc') }}
# clean up - old code
#      value_template: >
#        {% if states('sensor.temperatura_zewnetrzna_polnoc') | float > 100 %}
#          {{ "%.2f" | format ( ( states('sensor.temperatura_zewnetrzna_polnoc') | float ) - 655.36 )  }}
#        {% elif states('sensor.temperatura_zewnetrzna_polnoc') | float > 0 %}
#          {{ states('sensor.temperatura_zewnetrzna_polnoc') }}
#        {% else %}
#          -
#        {% endif %}

    temperatura_zewnetrzna_poludnie_przeliczona:
      unit_of_measurement: °C
#      entity_id: sensor.temperatura_zewnetrzna_poludnie
      value_template: >
        {{ states('sensor.temperatura_zewnetrzna_poludnie') }}
#      value_template: >
#        {% if states('sensor.temperatura_zewnetrzna_poludnie') | float > 100 %}
#          {{ "%.2f" | format ( ( states('sensor.temperatura_zewnetrzna_poludnie') | float ) - 655.36 )  }}
#        {% elif states('sensor.temperatura_zewnetrzna_poludnie') | float > 0 %}
#          {{ states('sensor.temperatura_zewnetrzna_poludnie') }}
#        {% else %}
#          -
#        {% endif %}
    temperatura_dol:
      unit_of_measurement: °C
#      entity_id: sensor.temperatura_salon_schody, sensor.temperatura_salon_przejscie
      value_template: >
        {{ "%.2f" | format (( states('sensor.temperatura_salon_schody') | float +  states('sensor.temperatura_salon_przejscie') | float ) / 2 ) }}
    temperatura_sypialnie:
      unit_of_measurement: °C
#      entity_id: sensor.temperatura_sypialnia_ady, sensor.temperatura_sypialnia_ewy, sensor.temperatura_sypialnia_rodzicow
      value_template: >
        {{ "%.2f" | format ( (  states('sensor.temperatura_sypialnia_ady') | float +  states('sensor.temperatura_sypialnia_rodzicow') | float +  states('sensor.temperatura_sypialnia_ewy') | float ) / 3 )  }}

- platform: command_line
  name: Moc wentylatora
  command: "cat /home/homeassistant/.homeassistant/scripts/fan_speed"
  scan_interval: 5
- platform: command_line
  name: log_db_file_size
  command: "du -m /home/homeassistant/.homeassistant/home-assistant_v2.db | cut -f1"
  unit_of_measurement: 'MB'
  value_template: '{{ value | int - 1 }}'

- platform: time_date
  display_options: 'date_time'

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /home
    - type: memory_free
    - type: memory_use
    - type: processor_use
#    - type: swap_free
#    - type: swap_use
    - type: since_last_boot

- platform: cpuspeed
  name: CPU

- platform: moon

#- platform: darksky
#  api_key: !secret darksky_api_key
#  update_interval: '00:10'
#  monitored_conditions:
##      - summary
##      - icon
##      - nearest_storm_distance
##      - nearest_storm_bearing
##      - precip_type
##      - precip_intensity
#    - precip_probability
#    - temperature
#    - apparent_temperature
##     - dew_point
#    - wind_speed
#    - wind_bearing
#    - cloud_cover
##      - humidity
#    - pressure
##      - visibility
##      - ozone
##      - minutely_summary
##      - hourly_summary
##      - daily_summary
##      - temperature_max
##      - temperature_min
##      - apparent_temperature_max
##      - apparent_temperature_min
##      - precip_intensity_max

# Weather Prediction
#  - platform: yr
#    monitored_conditions:
#      - temperature
#      - symbol
#      - precipitation
#      - windSpeed
#      - pressure
#      - windDirection
#      - humidity
#      - fog
#      - cloudiness
#      - lowClouds
#      - mediumClouds
#      - highClouds
#      - dewpointTemperature

- platform: wunderground
  api_key: !secret wunderground_api_key
  monitored_conditions:
#    - alerts # Current severe weather advisories
#    - dewpoint_c # Temperature in Celsius below which water droplets begin to condense and dew can form
#    - dewpoint_f # Temperature in Fahrenheit below which water droplets begin to condense and dew can form
#    - dewpoint_string # Text summary of dew point
    - temp_c # Current temperature in Celsius
    - feelslike_c # Feels like (or apparent) temperature in Celsius
#    - feelslike_f # Feels like (or apparent) temperature in Fahrenheit
#    - feelslike_string # Text summary of how the current temperature feels like
#    - heat_index_c # Heat index (combined effects of the temperature and humidity of the air) in Celsius
#    - heat_index_f # Heat index (combined effects of the temperature and humidity of the air) in Fahrenheit
#    - heat_index_string # Text summary of current heat index
#    - elevation # Elevation in feet
#    - location # City and State
#    - observation_time # Text summary of observation time
#    - precip_today_in # Total precipitation in inches
    - precip_today_metric # Total precipitation in metric units
#    - precip_today_string # Text summary of precipitation today
#    - precip_1d_mm [1d] # Forecasted precipitation intensity in millimeters
#    - precip_1d_in [1d] # Forecasted precipitation intensity in inches
#    - precip_1d [1d] # Forecasted precipitation probability in %
#    - pressure_in # Atmospheric air pressure in inches
    - pressure_mb # Atmospheric air pressure in millibars
    - pressure_trend # Atmospheric air pressure trend signal (+/-)
#    - relative_humidity # Relative humidity
#    - station_id # Your personal weather station (PWS) ID
#    - solarradiation # Current levels of solar radiation
#    - temperature_string # Temperature text combining Fahrenheit and Celsius
#    - temp_f # Current temperature in Fahrenheit
#    - temp_high_record_c # Maximum temperature measured in Celsius
#    - temp_high_record_f # Maximum temperature measured in Fahrenheit
#    - temp_low_record_c # Minimal temperature measured in Celsius
#    - temp_low_record_f # Minimal temperature measured in Fahrenheit
#    - temp_high_avg_c # Average high for today in Celsius
#    - temp_high_avg_f # Average high for today in Fahrenheit
#    - temp_low_avg_c # Average low for today in Celsius
#    - temp_low_avg_f # Average low for today in Fahrenheit
#    - temp_high_1d_c [1d] # Forecasted high temperature in Celsius
#    - temp_high_1d_f [1d] # Forecasted high temperature in Fahrenheit
#    - temp_low_1d_c [1d] # Forecasted low temperature in Celsius
#    - temp_low_1d_f [1d] # Forecasted low temperature in Fahrenheit
#    - UV # Current levels of UV radiation. See here for explanation.
#    - visibility_km # Average visibility in km
#    - visibility_mi # Average visibility in miles
    - weather # A human-readable text summary with picture from Wunderground.
#    - weather_1d [12h] # A human-readable weather forecast using imperial units.
#    - weather_1d_metric [12h] # A human-readable weather forecast using metric units.
#    - weather_1h [1h] # Weather conditions in 1 hour. (e.g. “Thunderstorm” etc.)
#    - wind_degrees # Wind degrees
#    - wind_dir # Wind direction
    - wind_gust_kph # Wind gusts speed in kph
#    - wind_gust_mph # Wind gusts speed in mph
#    - wind_gust_1d_kph [1d] # Max. forecasted Wind in kph
#    - wind_gust_1d_mph [1d] # Max. forecasted Wind in mph
#    - wind_kph # Current wind speed in kph
#    - wind_mph # Current wind speed in mph
#    - wind_1d_kph [1d] # Forecasted wind speed in kph
#    - wind_1d_mph [1d] # Forecasted wind speed in mph
#    - wind_string # Text summary of current wind conditions

#- platform: rest
#  name: Mobile Alerts
#  resource: https://www.data199.com/api/pv1/device/lastmeasurement/
#  method: POST
#  headers: 
#    Content-Type: application/x-www-form-urlencoded
##  payload: "deviceids=085EB94699C2&phoneid=847890155556"
##  payload: "deviceids=0B03232527AB&phoneid=847890155556"
#  payload: "deviceids=085EB94699C2,0B03232527AB&phoneid=847890155556"
#  json_attributes: 
#    - devices
#  value_template: '{{ value_json.success }}'
#  force_update: true


#- platform: template
#  sensors:
#    mobile_alerts_wind_speed:
#      unit_of_measurement: m/s
##      entity_id: sensor.mobile_alerts
#      value_template: >
#        {{ states.sensor.mobile_alerts.attributes.devices[1].measurement.ws }}
#    mobile_alerts_wind_gust:
#      unit_of_measurement: m/s
##      entity_id: sensor.mobile_alerts
#      value_template: >
#        {{ states.sensor.mobile_alerts.attributes.devices[1].measurement.wg }}
#    mobile_alerts_wind_dir:
##      unit_of_measurement: m/s
##      entity_id: sensor.mobile_alerts
#      value_template: >
#        {{ states.sensor.mobile_alerts.attributes.devices[1].measurement.wd }}
# The wind direction. 
# 0: North, 1: North-northeast, 2: Northeast, 3: Eastnortheast, 
# 4: East, 5: East-southeast, 6: Southeast, 7: South-Southeast, 
# 8: South, 9: South-southwest, 10: Southwest, 11: West-southwest, 
# 12: West, 13: West-northwest, 14: Northwest, 15: North-northwest
#    mobile_alerts_rain_temp:
#      unit_of_measurement: °C
##      entity_id: sensor.mobile_alerts
#      value_template: >
#        {{ states.sensor.mobile_alerts.attributes.devices[0].measurement.t1 }}
#    mobile_alerts_rain_val:
#      unit_of_measurement: mm
##      entity_id: sensor.mobile_alerts
#      value_template: >
#        {{ states.sensor.mobile_alerts.attributes.devices[0].measurement.r }}
#    mobile_alerts_rain_flip:
##      unit_of_measurement: m/s
##      entity_id: sensor.mobile_alerts
#      value_template: >
#        {{ states.sensor.mobile_alerts.attributes.devices[0].measurement.rf }}
## t1 : The measured temperature in celsius.
## r: The rain value in mm. 0.258 mm of rain are equal to one flip.
## rf : The flip count of the rain sensor. A flip equals 0.258 mm of rain.


- platform: rest
  name: Mobile Alerts 2
#  resource: https://www.data199.com/api/pv1/device/lastmeasurement/
  resource: http://www.data199.com:8080/api/v1/dashboard
  method: POST
  headers: 
#    Content-Type: application/x-www-form-urlencoded
    User-Agent: remotemonitor/248 CFNetwork/758.2.8 Darwin/15.0.0
    Accept-Language: en-us
    Content-Type: application/x-www-form-urlencoded; charset=utf-8
    Host: www.data199.com:8080

#  payload: "deviceids=085EB94699C2&phoneid=847890155556"
#  payload: "deviceids=0B03232527AB&phoneid=847890155556"
#  payload: "deviceids=085EB94699C2,0B03232527AB&phoneid=847890155556"
#  payload: "devicetoken=empty&vendorid=3b7984e0-10c4-4b24-a7c8-fe5c63848292&phoneid=Unknown&version=1.21&build=248&executable=Mobile Alerts&bundle=de.synertronixx.remotemonitor&lang=en&timezoneoffset=60&timeampm=true&usecelsius=true&usemm=true&speedunit=0&timestamp=1522665356&requesttoken=446737cb9160b6568f85a2f7d4131408&deviceids=0311A7526348,085EB94699C2,070CAAC50AAC,0B03232527AB"
  payload: devicetoken=empty&vendorid=3b7984e0-10c4-4b24-a7c8-fe5c63848292&phoneid=Unknown&version=1.21&build=248&executable=Mobile Alerts&bundle=de.synertronixx.remotemonitor&lang=en&timezoneoffset=60&timeampm=true&usecelsius=true&usemm=true&speedunit=0&timestamp=1522668714&requesttoken=939815597c63d6e05edfd66e40618207&deviceids=0311A7526348,085EB94699C2,070CAAC50AAC,0B03232527AB
  json_attributes: 
    - result
  value_template: '{{ value_json.success }}'
  force_update: true
