title: Złoty Potok
# Exclude entities from "Unused entities" view
#excluded_entities:
#  - weblink.router
views:
    # View tab title.
  - title: ZlotyPotok
    # Optional unique id for direct access /lovelace/${id}
    id: ZlotyPotok
    # Each view can have a different theme applied.
    theme: dark-mode
    # The cards to show on this view.
    cards:
        # The filter card will filter entities for their state
      - type: entity-filter
        entities:
          - device_tracker.krzysiek_dell
          - device_tracker.krzysiek_krzysiek
        state_filter:
          - 'home'
        card_config:
          type: glance
          title: People that are home

        # The picture entity card will represent an entity with a picture
      - type: picture-entity
        image: https://www.home-assistant.io/images/default-social.png
        entity: light.salon_lampka

    # Specify a tab icon if you want the view tab to be an icon.
  - icon: mdi:home-assistant
  # Title of the view. Will be used as the tooltip for tab icon
    title: Parter
    cards:
      - type: picture-elements
        title: Parter
        image: /local/local/parter.png
#        image: https://www.home-assistant.io/images/default-social.png
        elements:
          - type: service-button
            title: Lights Off
            style:
              top: 97%
              right: 00%
              padding: 0px
            service: light.turn_off
            service_data:
              entity_id: group.all_lights
          - type: state-icon
            entity: switch.lampa_jadalnia_sufit
            tap_action: toggle
            style:
              top: 20%
              left: 25%
              #'--paper-item-icon-color': yellow
          - type: state-icon
            entity: switch.lampa_salon_kinkiety
            tap_action: toggle
            style:
              top: 13%
              left: 25%
              #'--paper-item-icon-color': yellow
          - type: state-icon
            entity: switch.lampa_salon_kinkiety
            tap_action: toggle
            style:
              top: 13%
              left: 50%
              #'--paper-item-icon-color': yellow
          - type: state-icon
            entity: switch.lampa_salon_kinkiety
            tap_action: toggle
            style:
              top: 13%
              left: 75%
              #'--paper-item-icon-color': yellow
          - type: state-icon
            entity: switch.lampa_korytarz_dol
            tap_action: toggle
            style:
              top: 45%
              left: 50%
              #'--paper-item-icon-color': yellow
          - type: state-icon
            entity: light.salon_lampka
            tap_action: toggle
            style:
              top: 17%
              left: 56%
              #'--paper-item-icon-color': yellow
          - type: state-icon
            entity: light.salon_sufit
            tap_action: toggle
            style:
              top: 26%
              left: 75%
              #'--paper-item-icon-color': yellow
          - type: state-label
            entity: sensor.temperatura_salon_przejscie
            style:
              top: 30%
              left: 56%
              #'--paper-item-icon-color': yellow
          - type: state-icon
            entity: switch.lampa_salon_kanapa
            tap_action: toggle
            style:
              top: 35%
              left: 75%
              #'--paper-item-icon-color': yellow
          - type: state-label
            entity: sensor.temperatura_kuchnia
            style:
              top: 50%
              left: 25%
              #'--paper-item-icon-color': yellow
          - type: state-label
            entity: sensor.temperatura_wiatrolap
            style:
              top: 85%
              left: 50%
              #'--paper-item-icon-color': yellow

   # Entities card will take a list of entities and show their state.
  # Title of the entities card
  - title: testy
    cards:
      - type: glance
       # The entities here will be shown in the same order as specified.
       # Each entry is an entity ID or a map with extra options.
        entities:
          - light.salon_lampka
          - switch.lampa_jadalnia_sufit
          - entity: light.salon_sufit
      # Override the name to use
            name: Jakaś lampa
          - camera.kamera_brama
          - sensor.temperatura_zewnetrzna_polnoc_przeliczona
      - type: entities
       # The entities here will be shown in the same order as specified.
       # Each entry is an entity ID or a map with extra options.
        entities:
          - light.salon_lampka
          - switch.lampa_jadalnia_sufit
          - entity: light.salon_sufit
      # Override the name to use
            name: Jakaś lampa
          - camera.kamera_brama
          - sensor.temperatura_zewnetrzna_polnoc_przeliczona
      - type: picture-glance
        title: picture-glance
       # The entities here will be shown in the same order as specified.
       # Each entry is an entity ID or a map with extra options.
        entities:
          - light.salon_lampka
          - switch.lampa_jadalnia_sufit
#          - entity: light.salon_sufit
      # Override the name to use
#            name: Jakaś lampa
          - camera.kamera_brama
          - sensor.temperatura_zewnetrzna_polnoc_przeliczona
        image: /local/local/parter.png
# The markdown card will render markdown text.
      - type: markdown
        title: Lovelace
        content: Welcome to your **Lovelace UI**.
  - title: Kamery
    type: vertical-stack
    cards:
      - type: horizontal-stack
        cards:
          - type: picture-glance
            title: Salon
            entities: 
              - binary_sensor.living_room_motion
            camera_image: camera.kamera_salon
          - type: picture-glance
            title: Drzwi
            entities: 
              - binary_sensor.camera_door_motion
            camera_image: camera.kamera_drzwi
          - type: picture-glance
            title: Brama
            entities: 
              - binary_sensor.camera_gate_motion_2
            camera_image: camera.kamera_brama
